### ISSUE TITLE
Explosive carrot sound on the floor

### ISSUE THREAD

**Issue by Deevad** [Deevad/peppercarrot_ep18_translation#3]
BAM  !  A carrot hit the floor like a gun shot.  :-) Thanks @cgand for noticing this mini mistake. 
Maybe something more subtle?

![2016-30-07_selection_002](https://cloud.githubusercontent.com/assets/4021867/17273085/7e6bbd0c-56a9-11e6-9f1b-748e3d06ba29.png)

Proposition: 
- Toop!
- Bim !
- Tam !

**Comment by cgand** [comment]
Question is: "Which is the sound of a carrot falling on floor".

This sound, make by mistake by Carrot, got the attention of Pepper.

By the moment I've used "Clomp", but not sure about it.

**Comment by Willem3141** [comment]
In the Dutch translation I used _plof_ for now (which is the sound of something relatively heavy falling on the floor). The English equivalent would be _thud_. For French I have no idea, sorry :wink:

**Comment by Deevad** [comment]
For french version I'll go for  'poum !' I think.

**Comment by agryson** [comment]
I like @cgand 's '**Clomp**'. In English it's generally for heavy plodding of booted feet, but it 'sounds' like a carrot hitting the ground to me. 

If we wanna get more 'interpretive' we could go for:
- Plunk
- Fomp
- Bumpf

**Comment by Deevad** [comment]
'Clomp' also works for french. I think I'll aslo move to this.

**Comment by Gtkall** [comment]
Clonk or Plok works for Greek too.
